### DISCUSSION TITLE
bootstrap 5 sass form radius call Long and slow Render blocking GUI

### DISCUSSION THREAD

**Discussion by POMXARK** [apexcharts/apexcharts.js#3826] [General]
Why does it work like this? is it possible to optimize?
is it possible to render on the server side? or run render in another thread?

![apexchart_slow_lock_gui](https://github.com/apexcharts/apexcharts.js/assets/18720947/631bd3df-4bb8-42e3-aea8-28f33e79eb23)

```js
var chart = new ApexCharts(document.querySelector("#chart"), options);

            chart.updateOptions({
                series: dataset_apex_arr,
                xaxis: {
                    categories: categoriesArr
                }
            })
            }
```
<details>
  <summary>Objects for render</summary>
  
![image](https://github.com/apexcharts/apexcharts.js/assets/18720947/d6893827-4b9e-48d1-b153-2d9d0e215792)

![image](https://github.com/apexcharts/apexcharts.js/assets/18720947/d11b7e56-0f70-4d86-b2fe-38a1ed5d1b96)

![image](https://github.com/apexcharts/apexcharts.js/assets/18720947/3e759546-1686-4212-a7b3-05a52a294775)
</details>

**Comment by POMXARK** [comment]
Hello @brianlagunas 
found out what was causing such problems with long loading

bootstrap 5.2.3
node_modules/bootstrap/scss/forms/_input-group.scss

```scss
  &.has-validation {
    > :nth-last-child(n + 3):not(.dropdown-toggle):not(.dropdown-menu):not(.form-floating),
    > .dropdown-toggle:nth-last-child(n + 4),
    > .form-floating:nth-last-child(n + 3) > .form-control,
    > .form-floating:nth-last-child(n + 3) > .form-select {
      // @include border-end-radius(0);  // <-- this line
    }
  }
```

```css
.input-group.has-validation > :nth-last-child(n+3):not(.dropdown-toggle):not(.dropdown-menu):not(.form-floating),
.input-group.has-validation > .dropdown-toggle:nth-last-child(n+4),
.input-group.has-validation > .form-floating:nth-last-child(n+3) > .form-control,
.input-group.has-validation > .form-floating:nth-last-child(n+3) > .form-select {
  border-top-right-radius: 0;
  border-bottom-right-radius: 0;
}
```
