### DISCUSSION TITLE
Change Data

### DISCUSSION THREAD

**Discussion by alsa-it** [apexcharts/apexcharts.js#3884] [Q&A]
Hi,
i've got a problem with some Data in my Electricity-Dashboard:
On Monday my HomeAssistant VM was stopped for 3-4hours and didnt display the Data in this time.
Background:
Im reading my Electricity Meter with a RaspberryPi + NodeRED (QoS 0) and publish the Data via MQTT so my Homeassistant-VM (physical different device) can read those data and display it in my Dashboard.

I have a normal Homeassistant-Dashboard which uses the data from the home-assistant_v2.db (statistics). This DB was missing Data for Monday 13:00, 14:00 and 15:00 which caused the wrong Data in the Dashboard.
I Inserted some Data for those timestamps and it worked, the Data was shown in the Dashboard.

Not i wanted to try ApexCharts because of the possibility to show multiple sensors with different kinds of chart_types (bar / line in my case). My Problem now is, that my ApexChart displays the old, wrong data again although i changed those in the db.

Here is my ApexChart conf:

```
type: custom:apexcharts-card
graph_span: 7d
header:
  show: true
  title: Stromtarife - Test Chart
  show_states: true
  colorize_states: true
series:
  - entity: sensor.gesamttarif
    name: Gesamt
    curve: smooth
    type: line
    group_by:
      func: delta
  - entity: sensor.hochtarif
    name: Hochtarif
    type: column
    group_by:
      func: delta
  - entity: sensor.niedertarif
    name: Niedertarif
    type: column
    group_by:
      func: delta
```
Apex Chart:
![grafik](https://github.com/apexcharts/apexcharts.js/assets/136603180/1fcad072-d6ac-4e0b-ad10-e9524099b099)

HA-Chart:
![grafik](https://github.com/apexcharts/apexcharts.js/assets/136603180/930cd2c3-0867-4516-872f-7a79f8831a6a)

Yes, i initialised the sensor.gesamttarif only a few hours before the problem appeared.

Questions:
Where does ApexChart takes its data from?
Can i change that data like i did for the HA-Chart in the DB?
