### DISCUSSION TITLE
Does dataLabels.style.color  can support Automatic color matching?

### DISCUSSION THREAD

**Discussion by vaynevayne** [apexcharts/apexcharts.js#3989] [Ideas]
https://codepen.io/xboxyan/pen/bGjVbGj 

```jsx
<div class="box">
  <span class="txt">text</span>
</div>
```

```css
.box{
  color: #ffeb3b;
  background-color: currentColor;
}
.text{
  filter: grayscale(1) contrast(999) invert(1)
}
```
