### DISCUSSION TITLE
Request: Customize Legend Layout to Display Two Columns in Polar Area Charts

### DISCUSSION THREAD

**Discussion by AjImad** [apexcharts/apexcharts.js#4385] [General]
Dear apexcharts community,

I hope you're doing well.

I'm currently working on a project that utilizes the Polar Area Charts Basic feature in ApexCharts. I've encountered a scenario where I need to customize the legend layout.
Specifically, I would like to arrange the legend items into two columns instead of the default single-column layout.

Currently, the legend appears as shown in the first screenshot: 

![Screenshot from 2024-04-04 08-00-59](https://github.com/apexcharts/apexcharts.js/assets/83509351/189de740-a9ea-4fe7-b571-7e134a36c51c)

However, I'd like to achieve a layout similar to the second screenshot:

![Screenshot from 2024-04-04 08-01-23](https://github.com/apexcharts/apexcharts.js/assets/83509351/bc50591e-310d-4ca6-ac50-3bdc1a318979)

Could you please provide guidance on how to achieve this customization?

Best regards,
AJBAR Imad.

**Comment by EdSouthgate** [comment]
I second this. Looking to do exactly the same.

**Comment by alniv94** [comment]
any solution how to do this?  thanks

**Comment by Splinterjke** [comment]
VueJS example, but you get the idea.
```css
<style scoped>
:deep(.apexcharts-legend-marker) {
  flex-shrink: 0 !important;
}

:deep(.apexcharts-legend.apexcharts-align-center.apx-legend-position-right) {
  align-self: center;
  flex-direction: column !important;
  flex-wrap: wrap !important;
  max-height: 348px;
}
</style>
```
