### DISCUSSION TITLE
Pie chart - replace total with own entity

### DISCUSSION THREAD

**Discussion by stefanovich1** [apexcharts/apexcharts.js#4464] [Q&A]
Hello friends,
I am using the home assistant integration by romrider.
I want to integrate a autarky value in the middle of a donut instead of a total.
Can I transform the value in a autarky entity?

```
apex_config:
  dataLabels:
    style:
      fontSize: 18px
  legend:
    show: false
  plotOptions:
    pie:
      donut:
        labels:
          show: true
          value:
            show: true
            fontSize: 24px
            fontWeight: 600
            offsetY: 16
            formatter: |
              EVAL:function (value) {
                return parseFloat(value).toLocaleString() + " kWh";
                } 
          total:
            show: true
            label: Gesamt
            formatter: |
              EVAL: hass.entity
                return entity in %
                }
```
Any suggestions?

Thanks!
