### DISCUSSION TITLE
How to show a Home Assistant apexcharts-card when a header item is pushed?

### DISCUSSION THREAD

**Discussion by AdrieKoolen** [apexcharts/apexcharts.js#4921] [Q&A]
Hi, I’m using the apexcharts-card in Home Assistant to view the history of temperatures and humidity of the thermostat and 3 radiators in my living room:
![image](https://github.com/user-attachments/assets/396ddbf4-154f-4eed-b2dc-c70f4ad75b4d)
 
When I push the 15.1 °C / “Radiator achter” in the header, I get a popup window with detailed information on the entity:
![image](https://github.com/user-attachments/assets/985785e6-57b3-43b8-b5a4-ce507ca34a21)
 
What I want to achieve is to replace contents of this popup window with an apexcharts-card of my own design, instead of the Home Assistant card that is shown now. I’ve tried to do this with the following YAML:
```
type: custom:apexcharts-card
apex_config:
  chart:
    zoom:
      enabled: true
    toolbar:
      show: true
      tools:
        zoom: true
        zoomin: true
        zoomout: true
        pan: true
        reset: true
    autoScaleXaxis: true
  legend:
    position: top
    horizontalAlign: left
  ...
header:
  show: true
  title: Woonkamer
  show_states: true
  colorize_states: true
...
series:
  - entity: climate.smart_thermostaat_x_2
    ...
  - entity: sensor.smart_thermostat_x_humidity_2
    ...
  - entity: climate.smart_radiator_thermostat_x_4
    attribute: current_temperature
    unit: " °C"
    show:
      in_chart: false
    name: "Radiator keuken"
    yaxis_id: temperatuur
    header_actions:
      tap_action:
        action: navigate
        navigation_path: /home
  - entity: climate.smart_radiator_thermostat_x_5
    attribute: current_temperature
    unit: " °C"
    show:
      in_chart: false
    yaxis_id: temperatuur
    name: "Radiator achter"
  - entity: climate.smart_radiator_thermostat_x_3
    ...
  - entity: climate.smart_thermostaat_x_2
    ...
```
Now, when I push the 14.8 °C / “Radiator keuken” in the header. The current tab, containing the ‘Woonkamer’ card, is left and I’m redirected to the Overview tab. But the navigation_path appears to do something...
I’ve also got an apexcharts-card, showing the rPi CPU load and temperature. When I push on the Usage in its header, I get a popup window:
![image](https://github.com/user-attachments/assets/efca27ab-179e-4828-9297-0eafec06ceb4)
Ignore the Toolbar / Zoom icons, which are popping up from the apexcharts-card behind the popup window... 😏

I’ve got two questions:
1. What mechanism is used to decide on what card to show in the popup window when an item is pushed in an apexcharts-card header? I seems like it’s dependent on the specified entity in the YAML code.
2. How can I use apexcharts-card header_actions to show the contents of an apexcharts-card when a header item is pushed?

I’m not very experienced in Home Assistant, apexcharts-card and YAML, so forgive me when my questions are stupid or have trivial answers.

Regards,
Adrie Koolen
