### ISSUE TITLE
Chart download no background

### ISSUE THREAD

**Issue by melrefaie** [apexcharts/apexcharts.js#105]
1. Downloaded svg don't have background option 
Please see this example: https://codepen.io/anon/pen/LJJYra

2. How to control toolbar icons colors ?

**Comment by junedchhipa** [comment]
1. Yes, you're right. The background color doesn't appear in the exported SVG. I will look into it.

2. To control toolbar icons colors, you will have to do it in CSS like below
```CSS
.apexcharts-toolbar svg {
    fill: red;
}
```
