### ISSUE TITLE
Line breaks in pie chart tooltip

### ISSUE THREAD

**Issue by ws420** [apexcharts/apexcharts.js#1090]
Is it possible to include a line break in the tooltip of a pie chart?

\n or <br> doesn't work :(

Thanks

**Comment by junedchhipa** [comment]
Tooltip is built with HTML element, so it can be tweaked with CSS

```CSS
.apexcharts-tooltip .apexcharts-tooltip-y-group {
    display: flex;
    flex-direction: column;
}
```
