### ISSUE TITLE
Missing option to hide tooltip title

### ISSUE THREAD

**Issue by pribilinskiy** [apexcharts/apexcharts.js#121]
Just found out that there's no way to hide tooltip title in options, only through css

```css
.apexcharts-tooltip-title {
    display: none;
}
```
