### ISSUE TITLE
Format label text in Tooltip for long labels 

### ISSUE THREAD

**Issue by Martin36** [apexcharts/apexcharts.js#1229]
I have a grouped barchart where some of the series labels can be very long. This works fine on a desktop screen but on mobile the tooltip floats out of the screen, as you can see in the image [here](https://imgur.com/SJaHEHj).

My question is if there is a way to make the tooltip look better on mobile devices.

One idea of a solution is stripping the label if it is too long e.g. "A very super long label that will be way too long to show on a mobile device" would be stripped down to "A very super long label...." or similar. It may not be the best solution, since the label would loose information. 

Another way could be to set a fixed width of the tooltip so that the text would start on a new line.

Thanks for taking your time to read this

**Comment by junedchhipa** [comment]
There are 2 ways you can handle this.

One way is to format the label text in the `tooltip.y.title.formatter` function

```javascript
tooltip: {
  y: {
    title: {
      formatter: function(val) {
        return val.length > 15 ? val.slice(0, 15) + '...' : val
      }
    }
  }
}
```

Another way is to use CSS to make the text fixed width

```css
.apexcharts-tooltip-y-group {
    display: flex;
}

.apexcharts-tooltip-text-label {
  max-width: 80px;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}
```

**Comment by Martin36** [comment]
Using the follwing will make the label appear on multiple lines and making it work very well on a mobile screen
```css
.apexcharts-tooltip-text-label {
  max-width: 80px;
  white-space: initial;
  overflow: hidden;
  text-overflow: ellipsis;
}
```
