### ISSUE TITLE
Multiple colors or gradients for track in Radial bar charts

### ISSUE THREAD

**Issue by nee2shaji** [apexcharts/apexcharts.js#1842]
Currently, we can only specify a monotonous color for track in radial bar charts. Can we have a feature where we can have multiple colors for various ranges/angles for track? (I'm referring to something like the outer thinner track in the attached image)
![image](https://user-images.githubusercontent.com/7229969/90386204-d79d7b00-e0a1-11ea-9614-1bb6f3e13da8.png)

**Comment by junedchhipa** [comment]
Sorry, this is not possible and is difficult to achieve.

**Comment by LudovicLemaire** [comment]
> Currently, we can only specify a monotonous color for track in radial bar charts. Can we have a feature where we can have multiple colors for various ranges/angles for track? (I'm referring to something like the outer thinner track in the attached image)
> ![image](https://user-images.githubusercontent.com/7229969/90386204-d79d7b00-e0a1-11ea-9614-1bb6f3e13da8.png)

How did you achieve to get it green colored from 0 to 200, then orange from 200 to 275(?) and then red
Can't figure out how can I achieve what you did

**Comment by jacauc** [comment]
I "kinda" got it working, but on a radialbar the colorstops don't work properly.
In the attached you'll see it is supposed to go blue, green, orange, red, but in fact it seems to go back to orange after a certain value and red is around 75%.

Also, for some reason I had to do that colorstops backward.



![image](https://user-images.githubusercontent.com/18201320/234202079-22d12503-1909-40d8-b3db-9e6500fc8ec8.png)

```
apex_config:
  plotOptions:
    radialBar:
      startAngle: -90
      endAngle: 90
      dataLabels:
        name:
          fontSize: 22px
        value:
          fontSize: 16px
  fill:
    type: gradient
    gradient:
      colorStops:
        - offset: 0
          color: red
        - offset: 30
          color: orange
        - offset: 80
          color: green
        - offset: 100
          color: deepskyblue
```
