### ISSUE TITLE
resize problem when using flex

### ISSUE THREAD

**Issue by dackon** [apexcharts/apexcharts.js#1881]
# Bug report
charts are too slow to fit the resized window

## Codepen
[Codepen](https://codesandbox.io/s/react-basic-example-forked-trc3t)

## Explanation
1. Shrink the window, you can see the two charts redrawed many times to fit the window
2. Delete 'display: "flex"' from the first div, the two charts respond instantly when resize the window

Interestingly, if I set the width of the chart to "80%"  with flex style, the two charts redraw much more faster. Or delete one chart, the left one with width="99%", also works fine.

**Comment by astone2014** [comment]
This is the struggle with flexbox and how it calculates resizing. I've seen similar behavior.

Try wrapping the chart in a some container.
```css
.container {
    display: flex;
    flex-direction: column;
    height: 100%;
    width: 100%;
    box-sizing: border-box;
    overflow: hidden;
}

.chart {
    flex: 1;
    box-sizing: border-box;
    padding: 0;
    height: 100%;
    min-height: 0;
    width: 100%;
    overflow: auto;
}

chart-wrapper {
    width: 100%;
    height: 100%;
    display: block;
    overflow: hidden;
}
```

```html
    <div class="grid-widget-container">
      <div class="grid-widget">
       <!-- chart display block -->
      </div>
    </div>
```
