### ISSUE TITLE
Support for easier CSS styling of legend elements

### ISSUE THREAD

**Issue by stanislawosinski** [apexcharts/apexcharts.js#1883]
I'm using CSS to style various elements of the chart for easy switching between light and dark themes. For the data series, I use CSS along the lines of:

```css
.apexcharts-series[seriesName='Embedding'] circle {
  fill: var(--embedding-text-color) !important;
}
```

I'd like to use a similar pattern for the legend marker, but there's no corresponding custom attribute I could target in the selector, so I have to use less robust code:

```css
.apexcharts-legend-series:nth-child(1) .apexcharts-legend-marker {
  background: var(--embedding-text-color) !important;
}
```

Is there a way to insert a similar series-dependant attribute or CSS class to the marker elements too?
