### ISSUE TITLE
3.19.2 -> 3.19.3 Some Charts (Scatter/Bubble) not redrawing on parent resize.

### ISSUE THREAD

**Issue by astone2014** [apexcharts/apexcharts.js#1910]
**Is your feature request related to a problem? Please describe.**	
I'm having issues resizing scatter plot, bubble chart after upgrade from `3.19.2` -> `3.19.3`.

Just by downgrading to `apex-charts@3.19.2` my scatter and bubble charts resize more as expected.

**Describe the solution you'd like**	
Help me understand why I'm seeing this behavior with the version change.

**Describe alternatives you've considered**	
- Manually redraw charts by listening to parent resize events. 
- Sticking with 3.19.2 but that'd suck.

**Additional context**	
Here is a gif of the behavior:
![pqEzSJKGYE](https://user-images.githubusercontent.com/22425467/93555324-a5eb2e80-f943-11ea-8212-b275347016b2.gif)

The wrapper for the chart

```css
.grid-widget-container{
    display: flex;
    flex-direction: column;
    height: 100%;
    width: 100%;
    box-sizing: border-box;
    overflow: hidden;
}

.grid-widget {
    flex: 1;
    box-sizing: border-box;
    padding: 0;
    height: 100%;
    min-height: 0;
    width: 100%;
    overflow: auto;
}

chart-wrapper {
    width: 100%;
    height: 100%;
    display: block;
    overflow: hidden;
}
```

```html
    <div class="grid-widget-container">
      <div class="grid-widget">
        <div class="chart-wrapper">
          <!-- chart display block -->
        </div>
      </div>
    </div>
```
