### ISSUE TITLE
Color thresholds for graphic lines

### ISSUE THREAD

**Issue by schmurtzm** [apexcharts/apexcharts.js#2201]
**Describe the solution you'd like**	
Be able to change the color of a line in function of his Y value. 
Setting values example : 

```
color_thresholds:
  - value: 3800
    color: '#12f39c'
  - value: 3900
    color: '#f39c12'
  - value: 4000
    color: '#f32c12'
```

**Additional context**	
An example : 
![image](https://user-images.githubusercontent.com/7110113/106685346-82f6a980-65c8-11eb-8a74-f5e7a6920e7f.png)

As you can see the color line change (upt to 3800 : green , up to 3900 orange and for 4000 and up red)
