### ISSUE TITLE
Week numberson x-axis

### ISSUE THREAD

**Issue by PuckeyP** [apexcharts/apexcharts.js#3372]
Hi All,
How do I get the week numbers on the x-axis
I tried working with 
```
xaxis:
    type: 'numeric'

    labels:
      show: true
      formatter: function(value) { return value.toFixed(0) }

```
but I don't get the function right
PPee
