### ISSUE TITLE
Can't remove line under labels

### ISSUE THREAD

**Issue by timclausen** [apexcharts/apexcharts.js#395]
## Codepen
https://codepen.io/difedk/pen/wNYpVw
<img width="893" alt="Skærmbillede 2019-03-13 kl  10 15 05" src="https://user-images.githubusercontent.com/2226613/54267226-296ed700-4579-11e9-8e50-6879eaa80451.png">

## Explanation

- What is the behavior you expect?
I've tried to remove the line in the bottom, but it seems that the grid goes under the labels. How can this be removed?

**Comment by junedchhipa** [comment]
I will move the gridlines to a separate group so that you will be able to target using CSS last-child.

**Comment by timclausen** [comment]
Thanks.. When will this be deployed?

**Comment by junedchhipa** [comment]
Will be deployed this weekend.

You will be able to target gridlines with CSS like this

```css
.apexcharts-gridlines-horizontal .apexcharts-gridline:last-child {
   display: none;
}
```
