### ISSUE TITLE
how to remove download svg file? 

### ISSUE THREAD

**Issue by skdmkygo** [apexcharts/apexcharts.js#440]

**Comment by skdmkygo** [comment]
i mean, i want in toolbar just download for png

**Comment by junedchhipa** [comment]
I will provide an option to disable certain download options.

**Comment by junedchhipa** [comment]
```CSS
.apexcharts-menu-item.exportSVG {
  display: none;
}
```
