### ISSUE TITLE
Disable Tooltip animations

### ISSUE THREAD

**Issue by general-adhoc** [apexcharts/apexcharts.js#447]
https://codepen.io/junedchhipa/pen/BqbQpY

(Codepen is down ATM, but that codepen shows the sluggish behavior of tooltip animations).  

## Explanation

- What is the behavior you expect?

Cannot disable tooltip animations.

Tooltips animations are slow.  When disabling animations for the chart, the animations still exist for tooltips and markers.

Is there a way to improve the performance of animations for tooltips as it appears you cannot disable these?

Thank you

**Comment by junedchhipa** [comment]
Tooltips and markers animations are done with CSS.
To disable tooltip and marker animations globally

```css
.apexcharts-tooltip,
.apexcharts-tooltip.active,
.apexcharts-xaxistooltip,
.apexcharts-xaxistooltip.active,
.apexcharts-marker {
   transition: none;
}
```
