### ISSUE TITLE
Prints out PNGs and SVGs without overwriting custom/modified legend and markers.

### ISSUE THREAD

**Issue by MarcinJaracz** [apexcharts/apexcharts.js#4633]
### Description
For some reason, ApexCharts prints out `PNGs` and `SVGs` without overwriting custom/modified legend and markers.
I've installed `jsPDF` to download my chart to `.pdf` obviously, but it takes one of two files which are already unwanted due to its lack of my custom legend and markers.
In ApexCharts ther is a feature to make a custom marker even with [example](https://apexcharts.com/docs/options/legend/#:~:text=the%20marker%20point.-,customHTML%3A%20function,-Custom%20HTML%20element). Even if I modify the markers, they newer showed up in exported image.

### Steps to Reproduce

1.  For my custom markers I've used:
 ```javascript
// javascript
	legend: {
		horizontalAlign: 'left',
		markers: {	
			customHTML: function() {
				return `<span class="custom-marker"><i class="fas fa-square-check"></i></span>`;
			}
		},
		itemMargin: {
			horizontal: 10,
		},
	},
```
2. To modiffy styles I've wrote:
```css
/* css */
.apexcharts-legend {
    display: grid !important;
    grid-template-columns: repeat(5, 1fr) !important; 
    grid-template-rows: auto auto !important; 
    gap: 5px !important;
    max-width: 100% !important; 
    margin: 0 auto !important;
    padding: 0 !important; 
}

.apexcharts-legend-series:nth-child(odd) {
    grid-row: 1 !important; 
}

.apexcharts-legend-series:nth-child(even) {
    grid-row: 2 !important; 
}

.apexcharts-legend-marker, .apexcharts-legend-text {
    margin: 0 !important;
    display: flex !important; 
    align-items: center !important;
```

### Expected Behavior
My Expected behavior is in this image. As you can see, plotted data has it own legend with elements divided into columns with Awesome Font signs. In the right top corner You can see a Pdf icon for downloading this chart to `.pdf`
![propre_chart](https://github.com/user-attachments/assets/cf4497c9-074a-4bb6-a37d-9aa33a7aa223)

### Actual Behavior
And here is how it really behaves:
![mychart](https://github.com/user-attachments/assets/15877a30-99b8-4c8a-8de0-3ada0bba1091)
There are no markers, columns are gone. It basically returned to the default state.
### Reproduction Link
https://codepen.io/MarcinJaracz/pen/oNroZog
