### ISSUE TITLE
the colums dont line up with the xaxis names when grouping by day

### ISSUE THREAD

**Issue by nightmare1111** [apexcharts/apexcharts.js#5053]
```
type: custom:apexcharts-card
graph_span: 7d
apex_config:
  xaxis:
    labels:
      format: ddd
series:
  - entity: sensor.loft_temp_temperature
    name: TV
    type: column
    color: red
    opacity: 0.5
    stroke_width: 2
    float_precision: 2
    group_by:
      func: max
      duration: 1d
    yaxis_id: first
```
the colums dont line up with the xaxis names when grouping by day
