### ISSUE TITLE
the columns don't line up with the xaxis names when grouping by day

### ISSUE THREAD

**Issue by nightmare1111** [apexcharts/apexcharts.js#5058]
### Steps to Reproduce

1. create a bar chart graph
2. select 7 day span
3. group_by:
      func: max
      duration: 1d

### Expected Behaviour
I would expect if there is sufficient room to line up the bar chart names on the x axis with the bar charts

### Actual Behaviour
the names are off by as much as a complete bar using a 7 day span
### Reproduction Link

![Image](https://github.com/user-attachments/assets/186abce3-cb85-4b0b-8dc6-119a35bc7e34)

**Comment by nightmare1111** [comment]
```
type: custom:apexcharts-card
graph_span: 7d
apex_config:
  xaxis:
    labels:
      format: ddd
series:
  - entity: sensor.loft_temp_temperature
    name: TV
    type: column
    color: red
    opacity: 0.5
    stroke_width: 2
    float_precision: 2
    group_by:
      func: max
      duration: 1d
    yaxis_id: first
```
