### ISSUE TITLE
How to move toolbar to left side?

### ISSUE THREAD

**Issue by xxx44yyy** [apexcharts/apexcharts.js#609]

**Comment by junedchhipa** [comment]
```css
.apexcharts-toolbar {
    position: absolute;
    right: auto;
    left: 10px;
}
```
