### ISSUE TITLE
stacked columns |  legend items in wrong order

### ISSUE THREAD

**Issue by AlexKvrlp** [apexcharts/apexcharts.js#850]
## example

see  [stacked column documentation](https://apexcharts.com/javascript-chart-demos/column-charts/stacked-column-100/) for example

## Explanation

- What is the behavior you expect?
I expect that the series are in the same order than the legend items. In the demo I expect that the "Product A" legend item placed is at the bottom.
- What is happening instead?
The legend item of "Product A" is shown at the top of the legend. The "Product A" Series is at the bottom of the stacked column. Have a look at "Product A" at the demo.
- What error message are you getting?
no error message

**Comment by junedchhipa** [comment]
As the legend is created with HTML elements, you can easily inverse it with

```css
.apexcharts-legend.position-right, .apexcharts-legend.position-left {
    flex-direction: column-reverse;
    top: 0 !important;
}
```
